/* Fixtures are injected into a disposable localhost response, never production runtime. */
const assert=require('node:assert/strict'),path=require('node:path');
const {openHarness}=require('./gear-progression.helpers.cjs');
(async()=>{const h=await openHarness('gear-progression'),p=h.page;
const ev=fn=>p.evaluate(fn),click=a=>p.locator('.screen:not(.hidden) [data-action="'+a+'"]').first().click();
const start=async(cls='mage')=>p.evaluate(cls=>{__hollowlight.test.start(cls);__hollowlight.test.hold(true);},cls);
try {
 const stats=await ev(()=>{const t=__gearTest,g=__hollowlight.game,rows=[];
  for(const id of Object.keys(t.CLASSES)) {__hollowlight.test.start(id);__hollowlight.test.hold(true);g.char.equip={};const c=g.char,cls=t.CLASSES[id],d=t.derived(c);
   rows.push({name:id+' naked baseline',pass:d.hpMax===cls.hp+Math.max(0,c.stats.vit-2)*10+c.stats.vit*6&&d.mpMax===cls.mp+Math.max(0,c.stats.int-2)*6});
   for(const stat of ['str','int','dex','vit']) {const allocated=structuredClone(c),geared=structuredClone(c),paragon=structuredClone(c);allocated.stats[stat]+=10;geared.equip.ring=__hollowlight.test.item('copper-ring');geared.equip.ring.affixes=[{key:stat,val:10,label:stat}];paragon.paragonStats[stat]=10;
    const a=t.derived(allocated),b=t.derived(geared),q=t.derived(paragon);rows.push({name:id+' '+stat+' allocation/gear/paragon equivalence',pass:['hpMax','mpMax','dmg','crit','aspd'].every(k=>a[k]===b[k]&&a[k]===q[k])});}
  }
  // Equivalent base bonuses and affixes must give the same final combat/resource stats.
  __hollowlight.test.start('mage');g.char.equip={};
  for(const [id,b] of Object.entries(t.ITEM_BASES)) {if(!['weapon','armor','ring','amulet'].includes(b.type))continue;const a=structuredClone(g.char),c=structuredClone(g.char),it=__hollowlight.test.item(id),proxy=__hollowlight.test.item('copper-ring');
   // The proxy has an empty base and occupies the same slot; copy power to preserve the tradeoff.
   proxy.affixes=Object.entries(b.base||{}).map(([key,val])=>({key,val,label:key}));proxy.power=b.power||it.power;c.equip[b.type]=proxy;a.equip[b.type]=it;
   const x=t.derived(a),y=t.derived(c);rows.push({name:id+' base attribute application',pass:['hpMax','mpMax','dmg','def','crit','aspd','res'].every(k=>x[k]===y[k])});
  }
  for(const [id,s] of Object.entries(t.SETS)) {const c=structuredClone(g.char);c.equip={};for(const b of s.pieces)c.equip[t.ITEM_BASES[b].type]=__hollowlight.test.item(b);const bonus=t.computeSetBonuses(c);rows.push({name:id+' complete set bonus',pass:Object.entries(s.bonus).every(([k,v])=>bonus[k]===v)&&new Set(s.pieces.map(x=>t.ITEM_BASES[x].type)).size===3});}
  return rows;
 });
 for(const r of stats)h.check(r.name,r.pass);
 await start();const cannon=await ev(()=>{const t=__gearTest,g=__hollowlight.game;g.char.equip.weapon=__hollowlight.test.item('glassheart-blade');const d=t.derived(g.char);return {actual:d.breakdown.finalDmg===d.dmg&&d.breakdown.dps===Math.round(d.dmg*(1+Math.min(100,d.crit)/100*.8)*d.aspd),d};});h.check('Glass Cannon breakdown uses final damage',cannon.actual);
 // Actual DOM item comparison, focused pinch-equivalent click, save and Continue.
 await start();await ev(()=>{__hollowlight.game.char.inventory.push(__hollowlight.test.item('starfall-staff'));});await click('game-menu');await click('menu-inventory');await p.locator('[data-action="inv-open"][data-idx="2"]').click();
 h.check('base Intellect visible on item card',(await p.locator('#item-card').innerText()).includes('+3 Intellect'));
 const predicted=await ev(()=>{const g=__hollowlight.game,t=__gearTest,old=g.char.equip.weapon,a=t.derived(g.char);g.char.equip.weapon=g.char.inventory[2];const b=t.derived(g.char);g.char.equip.weapon=old;return {mp:b.mpMax-a.mpMax,dps:b.breakdown.dps-a.breakdown.dps};});const card=await p.locator('#item-card').innerText();h.check('comparison reflects mana including gear Intellect',card.includes('+'+predicted.mp+' MP'));h.check('comparison reflects final DPS',card.includes('+'+predicted.dps+' DPS'));
 await p.screenshot({path:path.join(h.out,'item-stats-fixed.png')});await p.locator('[data-action="item-equip"]').focus();await ev(()=>document.activeElement.click());const equipped=await ev(()=>{const g=__hollowlight.game;return {id:g.char.equip.weapon.id,d:__gearTest.derived(g.char)};});await p.reload();await p.waitForFunction(()=>window.__gearTest);await click('title-continue');await ev(()=>__hollowlight.test.hold(true));h.check('equipped upgraded item survives reload',await ev(()=>__hollowlight.game.char.equip.weapon.id),equipped.id);h.check('derived stats survive reload',await ev(()=>__gearTest.derived(__hollowlight.game.char)),equipped.d);
 // Failed and successful salvage are complete transactions, including gems and aspects.
 await start();await ev(()=>{const g=__hollowlight.game,it=__hollowlight.test.item('sanguine-fang');it.gems=['ruby','topaz'];it.sockets=2;g.char.inventory.push(it);while(g.char.inventory.length<24)g.char.inventory.push(__hollowlight.test.item('rusted-sword'));g.stashMode='craft';__gearTest.navigateTo('stash');__gearTest.renderCraft();});const before=await ev(()=>JSON.stringify(__hollowlight.game.char));await p.locator('[data-action="craft-salvage"][data-idx="2"]').click();h.check('full-bag salvage leaves all character state unchanged',await ev(()=>JSON.stringify(__hollowlight.game.char)),before);
 await ev(()=>{__hollowlight.game.char.inventory.pop();__gearTest.renderCraft();});await p.locator('[data-action="craft-salvage"][data-idx="2"]').click();h.check('successful salvage removes legendary and restores both gems',await ev(()=>{const c=__hollowlight.game.char;return c.inventory.length===24&&!c.inventory.some(i=>i.baseId==='sanguine-fang')&&['ruby','topaz'].every(id=>c.inventory.some(i=>i.baseId===id))&&c.aspects.includes('bloodthirst')&&c.craftDust>0;}));await p.reload();await p.waitForFunction(()=>window.__gearTest);h.check('salvage aspect and gems persist',await ev(()=>{const c=__hollowlight.game.save.char;return c.aspects.includes('bloodthirst')&&c.inventory.some(i=>i.baseId==='ruby')&&!c.inventory.some(i=>i.baseId==='sanguine-fang');}));
 // Crafting and stash preserve item identity, ownership, currencies and socketed bonuses.
 await start();const craft=await ev(()=>{const h=__hollowlight,g=h.game,t=__gearTest,c=g.char;c.inventory.push(h.test.item('iron-sword'));const idx=2,it=c.inventory[idx],before=JSON.stringify(c);t.craftUpgrade(idx);const poorSame=before===JSON.stringify(c);c.craftDust=1000;c.glassTears=10;c.gold=100000;c.aspects=['bloodthirst'];t.craftUpgrade(idx);t.craftAddSocket(idx);const dust=c.craftDust;c.inventory.push(h.test.item('ruby'));g.socketingItemIdx=idx;t.socketGem(c.inventory.length-1);g._imprintIdx=idx;t.imprintApply('bloodthirst');const id=it.id,owned=JSON.stringify(it);t.stashDeposit(c.inventory.findIndex(i=>i.id===id));const stashOwned=g.save.stash.some(i=>i.id===id)&&!c.inventory.some(i=>i.id===id);t.stashWithdraw(g.save.stash.findIndex(i=>i.id===id));const restored=c.inventory.find(i=>i.id===id);return {poorSame,rarity:it.rarity,socket:it.gems,dust:c.craftDust,expectedDust:dust-10,power:it.power,stashOwned,identity:JSON.stringify(restored)===owned,id};});
 h.check('unaffordable crafting never charges or changes item',craft.poorSame);h.check('rarity upgrade applied',craft.rarity,'magic');h.check('socket consumes gem and applies it',craft.socket,['ruby']);h.check('imprint charges exact cost',craft.dust,craft.expectedDust);h.check('imprint power retained',craft.power,'bloodthirst');h.check('stash deposit transfers exact item',craft.stashOwned);h.check('stash withdrawal retains all upgraded fields',craft.identity);
 await p.reload();await p.waitForFunction(()=>window.__gearTest);h.check('crafted item persists across reload',await p.evaluate(id=>{const it=__hollowlight.game.save.char.inventory.find(i=>i.id===id);return it?.power==='bloodthirst'&&it.gems[0]==='ruby'&&it.rarity==='magic';},craft.id));
 const xp=await ev(()=>{const h=__hollowlight,g=h.game,t=__gearTest;h.test.start('warrior');h.test.hold(true);g.char.level=98;g.char.xp=t.xpForLevel(98)-10;const need=t.xpForParagon(0);t.gainXp(need+23);const carry={level:g.char.level,paragon:g.char.paragonLevel,points:g.char.paragonPoints,xp:g.char.paragonXp};const skillItem=h.test.item('starfall-staff');g.char.inventory.push(skillItem);t.equipItemAt(2);const grant=t.getAvailableSkills().includes('starfall');g.char.selectedSkill='starfall';t.unequipSlot('weapon');return {carry,grant,fallback:t.getActiveSkillId()};});h.check('XP carries through99 into Paragon without loss',xp.carry,{level:99,paragon:1,points:1,xp:13});h.check('cross-class legendary skill available while equipped',xp.grant);h.check('removed granted skill falls back to class skill',xp.fallback,'whirlwind');
 await start();await ev(()=>{const g=__hollowlight.game;g.char.level=10;g.save.bestiary={skeleton:100};g.save.bossesKilled={crypts:1};while(g.char.inventory.length<24)g.char.inventory.push(__hollowlight.test.item('rusted-sword'));});await click('game-menu');await click('menu-journey');await p.locator('[data-action="journey-claim"][data-ch="ch1"]').click();
 const reward=await ev(()=>{const g=__hollowlight.game;return {id:g.save.stash[0]?.id,claimed:g.char.journeyClaimed,bag:g.char.inventory.length,gold:g.char.gold,ground:g.items.length};});h.check('full-bag Journey reward goes to stash',!!reward.id&&reward.bag===24&&reward.ground===0&&reward.claimed.includes('ch1'));
 await p.screenshot({path:path.join(h.out,'journey-reward-fixed.png')});await ev(()=>__gearTest.claimChapter('ch1'));h.check('repeated chapter claim does not duplicate reward',await ev(()=>__hollowlight.game.save.stash.length),1);h.check('repeated chapter claim does not duplicate currency',await ev(()=>__hollowlight.game.char.gold),reward.gold);
 await p.reload();await p.waitForFunction(()=>window.__gearTest);h.check('Journey item survives reload',await ev(()=>__hollowlight.game.save.stash[0]?.id),reward.id);
 const chapters=await ev(()=>{const t=__gearTest,g=__hollowlight.game,a=t.JOURNEY.find(x=>x.id==='ch3'),b=t.JOURNEY.find(x=>x.id==='ch4');g.save.bossesKilled={crypts:1,overgrowth:1,frostpeak:1,infernal:1,voidspire:1,hollowking:1};const o=b.objectives.find(o=>o.label==='Fell every biome boss');return {ch3Paragon:a.objectives.some(o=>o.label.includes('Paragon')),ch4Paragon:b.objectives.some(o=>o.label==='Reach Paragon 5'),target:o.tgt,count:o.cur()};});h.check('Journey Paragon milestone occurs only in final chapter',!chapters.ch3Paragon&&chapters.ch4Paragon);h.check('every biome milestone needs six actual biome bosses',{target:chapters.target,count:chapters.count},{target:6,count:5});
 for(const variant of ['infernal-cleared','voidspire-unlocked','already-migrated-false','new-save']) {
  await start();await p.evaluate(v=>{const s=__hollowlight.game.save;s.unlockedBiomes={crypts:true,overgrowth:false,frostpeak:false,infernal:false,voidspire:false};s.bossesKilled={};if(v==='infernal-cleared')s.bossesKilled.infernal=1;if(v==='voidspire-unlocked')s.unlockedBiomes.voidspire=true;if(v==='already-migrated-false'){s.unlockedBiomes.tempest=false;s.bossesKilled.infernal=1;}__gearTest.saveGame();},variant);
  await p.reload();await p.waitForFunction(()=>window.__gearTest);h.check(variant+' Tempest migration',await ev(()=>!!__hollowlight.game.save.unlockedBiomes.tempest),variant!=='new-save');
 }
 await start();const level=await ev(()=>{const t=__gearTest,c=__hollowlight.game.char,b={stat:c.statPoints,talent:c.talentPoints};t.gainXp(t.xpForLevel(1)+t.xpForLevel(2)+7);return {level:c.level,xp:c.xp,stat:c.statPoints-b.stat,talent:c.talentPoints-b.talent};});h.check('two level awards give exact stats and talent points',level,{level:3,xp:7,stat:6,talent:2});await click('levelup-ok');await click('game-menu');await click('menu-character');const mpBefore=await ev(()=>__hollowlight.game.char.mpMax);await p.locator('[data-action="spend-stat"][data-stat="int"]').click();h.check('stat allocation through UI consumes one point and increases mana',await ev(()=>({points:__hollowlight.game.char.statPoints,mp:__hollowlight.game.char.mpMax})),{points:5,mp:mpBefore+6});
 await ev(()=>__gearTest.navigateTo('talents'));h.check('talent lower row locked before prerequisite',await p.locator('[data-action="talent-alloc"][data-node="o_deadly"]').count(),0);await p.locator('[data-action="talent-alloc"][data-node="o_sharp"]').click();h.check('talent prerequisite opens next row',await p.locator('[data-action="talent-alloc"][data-node="o_deadly"]').count(),1);await p.locator('[data-action="talent-alloc"][data-node="o_deadly"]').click();h.check('two talent purchases consume two points',await ev(()=>__hollowlight.game.char.talentPoints),0);await click('talent-reset');h.check('talent reset refunds exact ranks',await ev(()=>({points:__hollowlight.game.char.talentPoints,ranks:__hollowlight.game.char.talents})),{points:2,ranks:{}});
 await ev(()=>__gearTest.navigateTo('passives'));h.check('passives cannot be purchased below level10',await p.locator('[data-action="unlock-passive"]').count(),0);await ev(()=>{const c=__hollowlight.game.char;c.level=10;c.tomes=2;__gearTest.navigateTo('passives');});const hpBefore=await ev(()=>__gearTest.derived(__hollowlight.game.char).hpMax);await p.locator('[data-action="unlock-passive"][data-passive="toughness"]').click();h.check('passive buys actual life bonus with one tome',await ev(()=>({hp:__hollowlight.game.char.hpMax,tomes:__hollowlight.game.char.tomes})),{hp:Math.floor(hpBefore*1.25),tomes:1});await p.locator('[data-action="unlock-passive"][data-passive="toughness"]').click();h.check('repeat passive purchase cannot spend again',await ev(()=>__hollowlight.game.char.tomes),1);await p.reload();await p.waitForFunction(()=>window.__gearTest);h.check('allocated progression survives reopening',await ev(()=>{const c=__hollowlight.game.save.char;return c.talentPoints===2&&c.statPoints===5&&c.passives.toughness&&c.tomes===1;}));
 h.check('no runtime errors',h.report.errors,[]);h.check('no external/cloud calls',h.report.external,[]);
} catch(e) {h.report.failure=e.stack;process.exitCode=1;console.error(e);}finally{await h.finish();}
})().catch(e=>{console.error(e);process.exit(1)});
