/* Read-only source audit: private function access exists only in this intercepted local test page. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/kgood/.codex/skills/develop-web-game/node_modules/playwright');
const appURL=process.env.REALM_URL||'http://127.0.0.1:5251',out=process.env.REALM_EVIDENCE||path.resolve(__dirname,'../../.visual-review/spire-systems/progression');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader']}),ctx=await browser.newContext({viewport:{width:600,height:600}});const errors=[];
await ctx.route('**/*',async route=>{const u=new URL(route.request().url());if(!['localhost','127.0.0.1'].includes(u.hostname))return route.abort();if(u.pathname==='/app.js'){const res=await route.fetch(),body=await res.text();const marker='window.__GL_DATA =';assert.ok(body.includes(marker));return route.fulfill({response:res,body:body.replace(marker,'window.__gearTest = { derived, rollItem, rollAffix, gainXp, xpForLevel, xpForParagon, applyDerivedToChar, equipItemAt, unequipSlot, craftSalvage, craftUpgrade, craftAddSocket, socketGem, imprintApply, rerollItem, reforgeKeepBest, claimChapter, showItemDetail, renderCharacter, renderSkills, openStash, renderCraft, openVendor, getActiveSkillId, getAvailableSkills, stashDeposit, stashWithdraw, vendorSell, spendParagon, spendParagonNode, spendStat, killEnemy, AFFIXES, ITEM_BASES, GEMS, POWERS, JOURNEY, SETS, BIOMES, ENEMIES, SKILLS, RUNES }; '+marker)});}return route.continue();});
const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(appURL+'/?test');await p.waitForFunction(()=>window.__gearTest&&window.__hollowlight?.test);await p.evaluate(()=>{__hollowlight.test.start('mage');__hollowlight.test.hold(true);});
const data=await p.evaluate(()=>{const h=__hollowlight,g=h.game,t=__gearTest;const reset=(cls='mage')=>{h.test.start(cls);h.test.hold(true);g.char.equip={weapon:null,armor:null,ring:null,amulet:null};};
const ignoredBases=Object.entries(t.ITEM_BASES).filter(([id,b])=>b.base&&Object.keys(b.base).some(k=>!['dmg','def','mp'].includes(k))).map(([id,b])=>({id,name:b.name,type:b.type,base:b.base}));
reset();const baseline=t.derived(g.char),baseDelta=[];for(const entry of ignoredBases){g.char.equip={weapon:null,armor:null,ring:null,amulet:null};g.char.equip[entry.type]=h.test.item(entry.id);const d=t.derived(g.char);baseDelta.push({...entry,deltas:{damage:d.dmg-baseline.dmg,life:d.hpMax-baseline.hpMax,mana:d.mpMax-baseline.mpMax,crit:d.crit-baseline.crit,stats:d.bonusStats}});}
reset();const affixBase=t.derived(g.char);g.char.equip.ring=h.test.item(Object.keys(t.ITEM_BASES).find(k=>t.ITEM_BASES[k].type==='ring'));g.char.equip.ring.affixes=[{key:'int',label:'Intellect',val:10}];const intellect=t.derived(g.char);g.char.equip.ring.affixes=[];const ringOnly=t.derived(g.char);g.char.equip.ring=null;g.char.stats.int+=10;const allocated=t.derived(g.char);
reset();const plain=t.derived(g.char);g.char.equip.weapon=h.test.item('rusted-sword');g.char.equip.weapon.power='glasscannon';const cannon=t.derived(g.char);
reset();const powerBase=Object.keys(t.ITEM_BASES).find(k=>t.ITEM_BASES[k].power),powerItem=h.test.item(powerBase);powerItem.gems=Object.keys(t.GEMS).slice(0,2);powerItem.sockets=2;g.char.inventory.push(powerItem);while(g.char.inventory.length<24)g.char.inventory.push(h.test.item('rusted-sword'));const salvageBefore={n:g.char.inventory.length,dust:g.char.craftDust,aspects:[...g.char.aspects]};t.craftSalvage(2);const salvageAfter={n:g.char.inventory.length,dust:g.char.craftDust,aspects:[...g.char.aspects],kept:g.char.inventory.some(it=>it.id===powerItem.id),power:t.ITEM_BASES[powerBase].power};
reset();g.char.level=99;g.char.xp=0;g.char.paragonXp=0;g.char.paragonLevel=0;g.char.paragonPoints=0;const need=t.xpForParagon(0);t.gainXp(need+17);const paragon={level:g.char.paragonLevel,points:g.char.paragonPoints,xp:g.char.paragonXp,expectedRemainder:17};
reset();g.char.level=98;g.char.xp=t.xpForLevel(98)-10;const toCap=t.xpForParagon(0);t.gainXp(toCap+23);const capCarry={level:g.char.level,paragon:g.char.paragonLevel,points:g.char.paragonPoints,xp:g.char.paragonXp,expectedRemainder:13};
reset('warrior');const equipBefore=t.derived(g.char);g.char.inventory.push(h.test.item('starfall-staff'));t.equipItemAt(2);const grant={available:t.getAvailableSkills(),class:g.char.classId,item:g.char.equip.weapon.baseId};g.char.selectedSkill='starfall';t.unequipSlot('weapon');grant.after=t.getActiveSkillId();
return {ignoredBaseCount:ignoredBases.length,ignoredBases:baseDelta,affixIntellect:{gearManaDelta:intellect.mpMax-ringOnly.mpMax,allocatedManaDelta:allocated.mpMax-affixBase.mpMax},glassCannon:{damage:cannon.dmg,breakdownDamage:cannon.breakdown.finalDmg,dps:cannon.breakdown.dps,expectedDps:Math.round(cannon.dmg*(1+Math.min(100,cannon.crit)/100*.8)*cannon.aspd)},salvageBefore,salvageAfter,paragon,capCarry,grant,journals:t.JOURNEY.map(x=>({id:x.id,name:x.name,reward:x.reward,objectives:x.objectives.map(o=>({name:o.label,target:o.tgt}))}))};});
await p.evaluate(()=>{const g=__hollowlight.game,t=__gearTest;__hollowlight.test.start('mage');__hollowlight.test.hold(true);g.char.inventory.push(__hollowlight.test.item('starfall-staff'));t.showItemDetail(2);});await p.screenshot({path:path.join(out,'base-stats-item.png')});fs.writeFileSync(path.join(out,'initial-audit.json'),JSON.stringify({data,errors},null,2));console.log(JSON.stringify(data,null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
