const fs=require('node:fs'),path=require('node:path'),{chromium}=require(path.join(require('node:os').homedir(),'.codex/skills/develop-web-game/node_modules/playwright'));
const baseline=false,out=path.resolve(process.env.LEVEL_FLOW_OUT || path.join(__dirname,'../../.visual-review/spire-systems/levels/regression-flow'));fs.mkdirSync(out,{recursive:true});
const source=fs.readFileSync(baseline?path.join(__dirname,'baseline-app.js'):path.join(__dirname,'../app.js'),'utf8'),report={checks:[],errors:[]};
const check=(name,pass,detail)=>report.checks.push({name,pass,detail});
(async()=>{const b=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const ctx=await b.newContext({viewport:{width:600,height:600},serviceWorkers:'block'});
await ctx.addInitScript(()=>{let seed=1;const native=Math.random;window.__seed=n=>{seed=n>>>0;window.__seedOn=true;};Math.random=()=>{if(!window.__seedOn)return native();seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};});
await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(!['localhost','127.0.0.1'].includes(u.hostname))return r.abort();if(u.pathname==='/app.js')return r.fulfill({contentType:'application/javascript',body:source.replace('window.__GL_DATA = {','window.__levels={killEnemy,enterDaily,enterRift,enterAbyss,enterGauntlet,enterThrone};window.__GL_DATA = {')});return r.continue();});
const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(process.env.TEST_URL || 'http://127.0.0.1:5251/?test=1');await p.waitForFunction(()=>window.__hollowlight?.test&&window.__GL?.ready);await p.evaluate(async()=>{await __GL.ready;__hollowlight.test.start('warrior');__hollowlight.test.hold(true);__seed(78);__hollowlight.enterBiome('crypts',1);__hollowlight.game.enemies=[];});
const start=await p.evaluate(()=>{const h=__hollowlight,p=h.game.world.player;return{x:p.x,y:p.y,canStand:h.test.canStand(p.x,p.y)};});
await p.screenshot({path:path.join(out,'spawn-seed78.png')});const motion=[];for(const key of ['ArrowUp','ArrowRight','ArrowDown','ArrowLeft']){await p.keyboard.down(key);await p.evaluate(()=>advanceTime(200));await p.keyboard.up(key);motion.push(await p.evaluate(()=>{const p=__hollowlight.game.world.player;return{x:p.x,y:p.y};}));}
const end=await p.evaluate(()=>{const h=__hollowlight,p=h.game.world.player;return{x:p.x,y:p.y,canStand:h.test.canStand(p.x,p.y)};});check('seed78 spawn is legal and can leave using actual arrows',start.canStand&&end.canStand&&motion.some(p=>Math.hypot(p.x-start.x,p.y-start.y)>1),{start,end,motion});
for(const biome of ['crypts','overgrowth','frostpeak','infernal','tempest','voidspire']){
await p.evaluate(biome=>{__hollowlight.test.start('warrior');__hollowlight.test.hold(true);__hollowlight.game.save.actsSeen={act1:true,act2:true,act3:true,act4:true,act5:true,act6:true,prologue:true};__seed(23);__hollowlight.enterBiome(biome,1);},biome);
for(let floor=1;floor<=3;floor++){const before=await p.evaluate(()=>{const g=__hollowlight.game,po=g.world.portals.find(x=>x.kind==='next');g.enemies=[];g.world.player.x=po.x;g.world.player.y=po.y;g._actionsFocus=false;__hollowlight.test.interact();return{floor:g.activeFloor,legal:__hollowlight.test.canStand(po.x,po.y),interaction:g.nearbyPortal?.kind};});await p.locator('#game [data-action=game-interact]').evaluate(el=>el.click());const after=await p.evaluate(()=>({floor:__hollowlight.game.activeFloor,biome:__hollowlight.game.activeBiomeId,boss:__hollowlight.game.enemies.filter(e=>e.boss).map(e=>e.id)}));check(biome+' floor '+floor+' focused-click descends once',before.legal&&before.interaction==='next'&&after.floor===floor+1&&after.biome===biome,{before,after});}
const boss=await p.evaluate(()=>{const g=__hollowlight.game,e=g.enemies.find(e=>e.boss),before={...g.save.bossesKilled};g.world.player.x=e.x;g.world.player.y=e.y+1;g.enemies=[e];e.hp=0;__levels.killEnemy(e);__GL.frame(g,16000);return{id:e.id,alive:g.bossAlive,counts:g.save.bossesKilled,unlocked:g.save.unlockedBiomes,returnPortal:g.world.portals.some(po=>po.kind==='town'&&Math.hypot(po.x-e.x,po.y-e.y)<.01),isBoss:g.world.isBoss};});check(biome+' boss defeat records biome and creates return',boss.isBoss&&boss.returnPortal&&boss.counts[biome]===1,boss);
while(await p.locator('[data-action=levelup-ok]:visible').count())await p.locator('[data-action=levelup-ok]:visible').click();
await p.evaluate(()=>{__hollowlight.test.interact();__GL.frame(__hollowlight.game,16000);});await p.screenshot({path:path.join(out,biome+'-boss-clear.png')});
await p.locator('#game [data-action=game-interact]').evaluate(el=>el.click());check(biome+' return portal arrives at Sanctuary',await p.evaluate(()=>__hollowlight.game.world.kind==='town'),await p.evaluate(()=>render_game_to_text()));
}
for(const kill of [false,true]){
 await p.evaluate(kill=>{__hollowlight.test.start('warrior');__hollowlight.test.hold(true);__levels.enterAbyss(1);if(kill){const e=__hollowlight.game.enemies.find(e=>!e.hazard);e.hp=0;__levels.killEnemy(e);}},kill);
 while(await p.locator('[data-action=levelup-ok]:visible').count())await p.locator('[data-action=levelup-ok]:visible').click();
 const before=await p.evaluate(()=>{const g=__hollowlight.game,po=g.world.portals.find(p=>p.kind==='town');g.world.player.x=po.x;g.world.player.y=po.y;__hollowlight.test.interact();return g.char.glassTears||0;});await p.locator('#game [data-action=game-interact]').evaluate(el=>el.click());const after=await p.evaluate(()=>__hollowlight.game.char.glassTears||0);check(kill?'Combat-earned Abyss exit retains one tear':'Fresh Abyss enter/leave gives no tears',after-before===(kill?1:0),{before,after});const rep=await p.evaluate(()=>__hollowlight.game.save.factionRep?.covenant||0);check(kill?'First Abyss kill earns entry favor exactly once':'Fresh Abyss enter/leave gives no Covenant favor',rep===(kill?4:0),rep);
}
for(const mode of ['rift','abyss']){
 await p.evaluate(mode=>{__hollowlight.test.start('warrior');__hollowlight.test.hold(true);__seed(522);if(mode==='rift')__levels.enterRift(1);else __levels.enterAbyss(1);const g=__hollowlight.game,po=g.world.portals.find(p=>p.kind===mode+'-next');g.world.player.x=po.x;g.world.player.y=po.y;__hollowlight.test.interact();},mode);
 await p.locator('#game [data-action=game-interact]').evaluate(el=>el.click());check(mode+' locked portal does not descend',await p.evaluate(mode=>{const g=__hollowlight.game;return g.screen==='game'&&(mode==='rift'?g.rift.level:g.abyss.floor)===1&&g.world.portals.some(p=>p.kind===mode+'-next'&&p.locked);},mode));
 const clear=await p.evaluate(mode=>{const g=__hollowlight.game,state=mode==='rift'?g.rift:g.abyss;let killed=0;while(state.kills<state.killsNeeded&&killed<100){const e=g.enemies.find(e=>!e.hazard&&!e._dead);if(!e)break;e.hp=0;__levels.killEnemy(e);killed++;}return{killed,kills:state.kills,needed:state.killsNeeded,portalOpen:g.world.portals.some(p=>p.kind===mode+'-next'&&!p.locked)};},mode);check(mode+' reachable kill quota unlocks portal',clear.portalOpen&&clear.kills>=clear.needed,clear);
 while(await p.locator('[data-action=levelup-ok]:visible').count())await p.locator('[data-action=levelup-ok]:visible').click();
 await p.locator('#game [data-action=game-interact]').evaluate(el=>el.click());
 if(mode==='abyss'){check('Abyss portal opens three boon choices',await p.locator('[data-action=abyss-pick]:visible').count()===3);await p.locator('[data-action=abyss-pick]:visible').first().focus();await p.keyboard.press('Enter');}
 check(mode+' descends once after unlocked activation',await p.evaluate(mode=>{const g=__hollowlight.game;return g.screen==='game'&&(mode==='rift'?g.rift.level:g.abyss.floor)===2;},mode));
 await p.screenshot({path:path.join(out,mode+'-floor2.png')});const tears=await p.evaluate(()=>{const g=__hollowlight.game,po=g.world.portals.find(p=>p.kind==='town');g.world.player.x=po.x;g.world.player.y=po.y;__hollowlight.test.interact();return g.char.glassTears||0;});await p.locator('#game [data-action=game-interact]').evaluate(el=>el.click());check(mode+' leave returns to Sanctuary and clears active mode',await p.evaluate(mode=>{const g=__hollowlight.game;return g.world.kind==='town'&&(mode==='rift'?!g.rift:!g.abyss?.active);},mode));if(mode==='abyss')check('Cleared Abyss floor retains reward even before next-floor combat',await p.evaluate(()=>__hollowlight.game.char.glassTears||0)===tears+1);
}
}catch(e){report.error=e.stack;process.exitCode=1;}finally{await b.close();report.failed=report.checks.filter(x=>!x.pass);report.passed=!report.error&&!report.errors.length&&!report.failed.length;if(!report.passed)process.exitCode=1;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,failed:report.failed,error:report.error,errors:report.errors}));}})();
