const fs=require('node:fs'),path=require('node:path');
const {chromium}=require(path.join(require('node:os').homedir(),'.codex/skills/develop-web-game/node_modules/playwright'));
const out=path.resolve(process.env.LEVEL_TEST_OUT || path.join(__dirname,'../../.visual-review/spire-systems/levels/regression'));fs.mkdirSync(out,{recursive:true});const source=fs.readFileSync(path.join(__dirname,'../app.js'),'utf8');
const report={checks:[],errors:[],externalBlocked:[]};
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const ctx=await browser.newContext({viewport:{width:600,height:600},serviceWorkers:'block'});
 await ctx.addInitScript(()=>{let seed=1;const native=Math.random;window.__seed=n=>{seed=n>>>0;window.__seedOn=true;};Math.random=()=>{if(!window.__seedOn)return native();seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};});
 await ctx.route('**/*',async r=>{const u=new URL(r.request().url());if(!['localhost','127.0.0.1'].includes(u.hostname)){report.externalBlocked.push(u.origin);return r.abort();}if(u.pathname==='/app.js')return r.fulfill({contentType:'application/javascript',body:source.replace('window.__GL_DATA = {','window.__levels = {generateDungeon,enterDaily,enterGauntlet,enterThrone,enterNightmare,enterRift,enterAbyss,killEnemy,GAUNTLET_BOSSES,withSeededRandom,sampleRand:()=>rand()}; window.__GL_DATA = {')});return r.continue();});
 const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(process.env.TEST_URL || 'http://127.0.0.1:5251/?test=1');await p.waitForFunction(()=>window.__hollowlight?.test&&window.__GL?.ready);await p.evaluate(async()=>{await __GL.ready;__hollowlight.test.start('warrior');__hollowlight.test.hold(true);});
 report.generation=await p.evaluate(()=>{
  const all=[],failures=[],g=__hollowlight.game;
  function analysis(w){const reach=new Set(),dist=new Map(),q=[[Math.floor(w.player.x),Math.floor(w.player.y)]],key=(x,y)=>y*w.w+x;let startOk=w.grid[q[0][1]][q[0][0]]===0;if(startOk){reach.add(key(...q[0]));dist.set(key(...q[0]),0);}else q.length=0;
   for(let i=0;i<q.length;i++){const [x,y]=q[i];for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=key(nx,ny);if(w.grid[ny]?.[nx]===0&&!reach.has(k)){reach.add(k);dist.set(k,dist.get(key(x,y))+1);q.push([nx,ny]);}}}
   const accessible=o=>reach.has(key(Math.floor(o.x),Math.floor(o.y))),blocked=[];if(!startOk)blocked.push({kind:'spawn',...w.player});
   for(const[kind,list]of[['portal',w.portals],['shrine',w.shrines],['enemy',w.enemies],['loot',w.loot]])for(const o of list||[])if(!accessible(o))blocked.push({kind,id:o.id||o.kind||o.type,x:o.x,y:o.y,tile:w.grid[Math.floor(o.y)]?.[Math.floor(o.x)]});
   let openTiles=0;for(const row of w.grid)for(const v of row)if(v===0)openTiles++;
   const end=w.portals.find(o=>o.kind==='next')||w.enemies.find(o=>o.boss);return{startOk,blocked,openTiles,reachable:reach.size,rooms:w.rooms.length,shapes:w.rooms.map(r=>r.shape),specials:w.rooms.filter(r=>r.special).map(r=>r.special),enemies:w.enemies.length,exitDistance:end?dist.get(key(Math.floor(end.x),Math.floor(end.y))):null,exitEuclidean:end?Math.hypot(end.x-w.player.x,end.y-w.player.y):null,nonHazard:w.enemies.filter(e=>!e.hazard).length};
  }
  window.__mapAnalysis=analysis;
  for(let seed=1;seed<=300;seed++)for(const b of __hollowlight.BIOMES)for(let floor=1;floor<=4;floor++){__seed(seed);const w=__levels.generateDungeon(b,floor),a=analysis(w),record={seed,biome:b.id,floor,...a};all.push(record);if(a.blocked.length||a.reachable!==a.openTiles)failures.push(record);}
  const special=[];for(let seed=1;seed<=100;seed++)for(const mode of ['isRift','isAbyss'])for(const floor of [1,4,11,25]){__seed(seed);const w=__levels.generateDungeon(__hollowlight.BIOMES[5],floor,{[mode]:true,noBoss:true,enemyPerRoom:[3,5]}),a=analysis(w);special.push({seed,mode,floor,pass:a.startOk&&!a.blocked.length&&a.openTiles===a.reachable&&a.nonHazard>=Math.max(6,Math.floor(w.enemies.length*.7)),blocked:a.blocked});}
  const layouts=__hollowlight.BIOMES.map(b=>{__seed(112);return JSON.stringify(__levels.generateDungeon(b,2).grid);});
  return{maps:all.length,failures,special:{maps:special.length,failures:special.filter(x=>!x.pass)},sameSeedDistinctBiomes:new Set(layouts).size,summary:__hollowlight.BIOMES.map(b=>{const a=all.filter(x=>x.biome===b.id);return{biome:b.id,maps:a.length,failed:a.filter(x=>x.blocked.length).length,rooms:[Math.min(...a.map(x=>x.rooms)),Math.max(...a.map(x=>x.rooms))],exitDistance:[Math.min(...a.map(x=>x.exitDistance).filter(Number.isFinite)),Math.max(...a.map(x=>x.exitDistance).filter(Number.isFinite))],closeExit:a.filter(x=>x.exitDistance<12).length,shapes:[...new Set(a.flatMap(x=>x.shapes))],arena:a.filter(x=>x.specials.includes('arena')).length,vault:a.filter(x=>x.specials.includes('vault')).length};}),examples:all.slice(0,24)};
 });
 fs.writeFileSync(path.join(out,'generation.json'),JSON.stringify(report.generation,null,2));
 report.flow=await p.evaluate(()=>{const g=__hollowlight.game,result={};const layout=()=>JSON.stringify(g.world.grid);__seed(101);__levels.enterDaily();const d1={layout:layout(),biome:g.world.biomeId,mod:g.world.dailyMod};__hollowlight.enterTown();__seed(102);__levels.enterDaily();result.daily={sameBiome:d1.biome===g.world.biomeId,sameMod:d1.mod===g.world.dailyMod,sameLayout:d1.layout===layout()};__seed(811);const expected=__levels.sampleRand();__seed(811);try{__levels.withSeededRandom(32,()=>{__levels.sampleRand();throw new Error('test');});}catch{}result.randomRestoredAfterError=__levels.sampleRand()===expected;__hollowlight.enterTown();__levels.enterGauntlet();result.gauntlet={ids:__levels.GAUNTLET_BOSSES,missingBiomeBosses:__hollowlight.BIOMES.filter(b=>!__levels.GAUNTLET_BOSSES.includes(b.boss)).map(b=>b.boss)};return result;});
 report.finished=true;report.passed=!report.errors.length&&!report.generation.failures.length&&!report.generation.special.failures.length&&report.generation.sameSeedDistinctBiomes===6&&report.flow.daily.sameLayout&&report.flow.randomRestoredAfterError&&!report.flow.gauntlet.missingBiomeBosses.length;if(!report.passed)process.exitCode=1;
}catch(e){report.error=e.stack;process.exitCode=1;}finally{await browser.close();fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({maps:report.generation?.maps,failures:report.generation?.failures.length,summary:report.generation?.summary,flow:report.flow,errors:report.errors,error:report.error}));}})();
