const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||require('node:path').join(require('node:os').homedir(),'.codex/skills/develop-web-game/node_modules/playwright'));
const base=process.env.REALM_URL||'http://127.0.0.1:5265';
const out=process.env.REALM_EVIDENCE||path.resolve(__dirname,'../../.visual-review/spire-feel/controls/current');
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader']}),checks=[],errors=[],outbound=[],metrics={};
 const context=await browser.newContext({viewport:{width:600,height:600},serviceWorkers:'block'});
 async function isolate(c){await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.origin!==new URL(base).origin){outbound.push(u.href);return r.abort();}if(u.pathname==='/movement-prior-page')return r.fulfill({contentType:'text/html',body:'<title>Previous page</title>Previous page'});if(u.pathname==='/app.js'){const res=await r.fetch(),source=await res.text();assert.ok(source.includes('save: saveGame, interact: tickInteraction,'),'Test hook anchor exists');return r.fulfill({response:res,body:source.replace('save: saveGame, interact: tickInteraction,','movementStep: tickPlayer, pollPad: pollGamepad, save: saveGame, interact: tickInteraction,')});}return r.continue();});}
 await isolate(context);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/?test');await page.waitForFunction(()=>window.__hollowlight?.test);
 const run=fn=>page.evaluate(fn),check=async(name,fn)=>{try{await fn();checks.push({name,pass:true});}catch(e){checks.push({name,pass:false,error:e.message});}};
 // Test-only open area and walls keep the simulation deterministic. The app source
 // response exposes its existing movement routine; the checkout is never modified.
 await run(()=>{
   window.feelFixture=(shape='open')=>{const h=__hollowlight;h.test.hold(true);h.test.start('warrior');const g=h.game,w=g.world;w.w=w.h=40;w.grid=Array.from({length:40},(_,y)=>Array.from({length:40},(_,x)=>x===0||y===0||x===39||y===39||(shape==='wall'&&x===18)||(shape==='corner'&&(x===18||y===18))||(shape==='obstacle'&&x===18&&y===18)?1:0));Object.assign(w.player,{x:15.5,y:15.5,skillCd:0,dashCd:0});g.enemies=[];g.items=[];g.projectiles=[];w.portals=[];w.npcs=[];w.shrines=[];g.char.autoPlay=false;g.char.autoPotion=false;g._msMul=1;g.nearbyNpc=g.nearbyPortal=g.nearbyShrine=g.nearbyItem=null;};
   window.feelKey=(key,type='keydown')=>document.dispatchEvent(new KeyboardEvent(type,{key,bubbles:true,cancelable:true}));
   window.feelTap=key=>{feelKey(key);feelKey(key,'keyup');};
   window.feelStep=(seconds,dt=1/60)=>{let t=0;while(t<seconds-1e-9){const step=Math.min(dt,seconds-t);__hollowlight.test.movementStep(step);if(!__hollowlight.test.canStand(__hollowlight.game.world.player.x,__hollowlight.game.world.player.y))throw new Error('Movement entered solid geometry');t+=step;}};
   window.feelPos=()=>{const p=__hollowlight.game.world.player;return{x:p.x,y:p.y};};
 });
 const fixture=shape=>page.evaluate(shape=>feelFixture(shape),shape);
 const pos=()=>run(()=>feelPos());
 const close=(actual,expected,tolerance=.015)=>assert.ok(Math.abs(actual-expected)<=tolerance,`${actual} expected ${expected} ±${tolerance}`);
 const unchanged=(a,b)=>{close(a.x,b.x,1e-8);close(a.y,b.y,1e-8);};
 for(const [key,dx,dy]of[['ArrowRight',1,0],['ArrowLeft',-1,0],['ArrowDown',0,1],['ArrowUp',0,-1]])await check('isolated neural '+key+' swipe travels about2.3tiles',async()=>{await fixture();await page.keyboard.press(key);await run(()=>feelStep(1));const p=await pos();const d=(p.x-15.5)*dx+(p.y-15.5)*dy;metrics[key]=d;assert.ok(d>=2.2&&d<=2.4,String(d));close((p.x-15.5)*dy+(p.y-15.5)*dx,0);});
 await check('swipe travel is consistent at20,30and60frames/sec',async()=>{const distances=await run(()=>[1/60,1/30,.05].map(dt=>{feelFixture();feelTap('ArrowRight');feelStep(1,dt);return feelPos().x-15.5;}));metrics.frameRates=distances;assert.ok(Math.max(...distances)-Math.min(...distances)<.015,JSON.stringify(distances));});
 await check('fresh opposite swipe reverses on the next frame',async()=>{await fixture();const r=await run(()=>{feelTap('ArrowRight');feelStep(.08);const before=feelPos();feelTap('ArrowLeft');feelStep(1/60);return{before,after:feelPos()};});assert.ok(r.after.x<r.before.x);close(r.after.y,r.before.y);});
 await check('two sub-frame opposite swipes use the latest direction',async()=>{await fixture();const p=await run(()=>{feelTap('ArrowRight');feelTap('ArrowLeft');feelStep(1);return feelPos();});assert.ok(p.x<=13.3&&p.x>=13.1,JSON.stringify(p));});
 await check('fresh perpendicular swipe turns without carrying old axis drift',async()=>{await fixture();const r=await run(()=>{feelTap('ArrowRight');feelStep(.08);const before=feelPos();feelTap('ArrowUp');feelStep(.5);return{before,after:feelPos()};});close(r.before.x,r.after.x);assert.ok(r.after.y<r.before.y-2.2);});
 await check('held keyboard retains full speed and stops on release',async()=>{await fixture();await page.keyboard.down('ArrowRight');await run(()=>feelStep(1));const held=await pos();close(held.x-15.5,10,.03);await page.keyboard.up('ArrowRight');await run(()=>feelStep(.5));const after=await pos();metrics.keyboardReleaseDrift=after.x-held.x;unchanged(held,after);});
 await check('diagonal held movement has the same speed',async()=>{await fixture();await page.keyboard.down('ArrowRight');await page.keyboard.down('ArrowDown');await run(()=>feelStep(1));const p=await pos();await page.keyboard.up('ArrowRight');await page.keyboard.up('ArrowDown');close(Math.hypot(p.x-15.5,p.y-15.5),10,.03);});
 await check('held input cannot tunnel through a wall',async()=>{await fixture('wall');await page.keyboard.down('ArrowRight');await run(()=>feelStep(2,.05));await page.keyboard.up('ArrowRight');const p=await pos();assert.ok(p.x<=17.780001&&p.x>17.6);close(p.y,15.5);});
 await check('oblique movement slides along the wall without penetration',async()=>{await fixture('wall');await page.keyboard.down('ArrowRight');await page.keyboard.down('ArrowDown');await run(()=>feelStep(1,.05));await page.keyboard.up('ArrowRight');await page.keyboard.up('ArrowDown');const p=await pos();assert.ok(p.x<=17.780001&&p.y>21);});
 await check('inside corners stop both axes and cannot eject the player',async()=>{await fixture('corner');await page.keyboard.down('ArrowRight');await page.keyboard.down('ArrowDown');await run(()=>feelStep(2,.05));await page.keyboard.up('ArrowRight');await page.keyboard.up('ArrowDown');const p=await pos();assert.ok(p.x<=17.780001&&p.y<=17.780001);assert.ok(p.x>17.5&&p.y>17.5);});
 await check('a single decoration tile cannot be crossed diagonally',async()=>{await fixture('obstacle');await run(()=>{feelTap('ArrowRight');feelKey('ArrowDown');feelStep(.8,.05);feelKey('ArrowDown','keyup');feelStep(.5);});assert.equal(await run(()=>__hollowlight.test.canStand(feelPos().x,feelPos().y)),true);});
 await check('context action immediately cancels a running swipe',async()=>{await fixture();const r=await run(()=>{feelTap('ArrowRight');feelStep(.08);const before=feelPos();feelTap('Enter');feelStep(.5);return{before,after:feelPos()};});unchanged(r.before,r.after);});
 await check('focused-element pinch click also cancels movement',async()=>{await fixture();const r=await run(()=>{feelTap('ArrowRight');feelStep(.08);const before=feelPos();document.activeElement.click();feelStep(.5);return{before,after:feelPos()};});unchanged(r.before,r.after);});
 await check('Escape menu freezes simulation and Resume has no stale movement',async()=>{await fixture();await page.keyboard.press('ArrowRight');await run(()=>advanceTime(80));await page.keyboard.press('Escape');const before=await pos();await run(()=>advanceTime(500));assert.equal(await run(()=>__hollowlight.game.screen),'menu');unchanged(before,await pos());await page.keyboard.press('Escape');assert.equal(await run(()=>__hollowlight.game.screen),'game');await run(()=>advanceTime(500));unchanged(before,await pos());});
 for(const key of ['BrowserBack','GoBack','Backspace'])await check(key+' opens the in-game menu and returns safely',async()=>{await fixture();await page.evaluate(key=>feelKey(key),key);assert.equal(await run(()=>__hollowlight.game.screen),'menu');await page.evaluate(key=>feelKey(key,'keyup'),key);await page.keyboard.press('Escape');assert.equal(await run(()=>__hollowlight.game.screen),'game');});
 await check('in-game Back action opens the menu even without menu history',async()=>{await fixture();await run(()=>{const b=document.createElement('button');b.dataset.action='back';document.querySelector('#game').appendChild(b);b.click();b.remove();});assert.equal(await run(()=>__hollowlight.game.screen),'menu');});
 await check('window blur cancels a swipe and opens the menu',async()=>{await fixture();await page.keyboard.press('ArrowRight');await run(()=>advanceTime(80));const before=await pos();await run(()=>window.dispatchEvent(new Event('blur')));assert.equal(await run(()=>__hollowlight.game.screen),'menu');await run(()=>advanceTime(500));unchanged(before,await pos());await page.keyboard.press('Escape');await run(()=>advanceTime(500));unchanged(before,await pos());});
 await check('background visibility cannot continue movement or restart it on return',async()=>{await fixture();await page.keyboard.press('ArrowRight');await run(()=>advanceTime(80));const before=await pos();await run(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));advanceTime(500);Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await run(()=>__hollowlight.game.screen),'menu');unchanged(before,await pos());await page.keyboard.press('Escape');await run(()=>advanceTime(500));unchanged(before,await pos());});
 await check('zone change cancels the old held key and pending swipe',async()=>{await fixture();await page.keyboard.down('ArrowRight');await run(()=>{advanceTime(60);__hollowlight.enterBiome('crypts',1);__hollowlight.game.enemies=[];__hollowlight.test.hold(true);});const before=await pos();await page.keyboard.up('ArrowRight');await run(()=>advanceTime(500));unchanged(before,await pos());});
 await run(()=>{window.feelPad={connected:true,axes:[0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>window.feelPad?[feelPad]:[]});});
 const pad=xy=>page.evaluate(xy=>{feelPad.axes=xy;__hollowlight.test.pollPad();},xy);
 await check('controller hold moves at full speed and release stops immediately',async()=>{await fixture();await pad([1,0]);await run(()=>feelStep(1));const before=await pos();close(before.x-15.5,10,.03);await pad([0,0]);await run(()=>feelStep(.5));unchanged(before,await pos());});
 await check('sub-frame controller tap is not lost or inflated into a long swipe',async()=>{await fixture();await pad([1,0]);await pad([0,0]);await run(()=>feelStep(.5));const d=(await pos()).x-15.5;assert.ok(d>0&&d<=.2,String(d));});
 await check('controller disconnect clears held movement',async()=>{await fixture();await pad([1,0]);await run(()=>feelStep(.1));const before=await pos();await run(()=>{window.feelPad=null;window.dispatchEvent(new Event('gamepaddisconnected'));__hollowlight.test.pollPad();feelStep(.5);});unchanged(before,await pos());});
 await check('legacy character survives control use and reload',async()=>{const legacy=JSON.parse(fs.readFileSync(path.join(__dirname,'legacy-save.json'),'utf8'));await page.evaluate(save=>localStorage.setItem('hollowlight_save_v2',JSON.stringify(save)),legacy);await page.reload();await page.waitForFunction(()=>window.__hollowlight?.test);await page.locator('[data-action="title-continue"]').click();await run(()=>__hollowlight.test.hold(true));const before=await run(()=>{const c=__hollowlight.game.char;return{classId:c.classId,level:c.level,gold:c.gold,inventory:c.inventory,equipped:c.equipped};});await page.keyboard.press('Escape');await run(()=>__hollowlight.test.save());await page.reload();await page.waitForFunction(()=>window.__hollowlight?.test);await page.locator('[data-action="title-continue"]').click();await run(()=>__hollowlight.test.hold(true));assert.deepEqual(await run(()=>{const c=__hollowlight.game.char;return{classId:c.classId,level:c.level,gold:c.gold,inventory:c.inventory,equipped:c.equipped};}),before);});
 const phoneContext=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,serviceWorkers:'block'});await isolate(phoneContext);const phone=await phoneContext.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto(base+'/?test');await phone.waitForFunction(()=>window.__hollowlight?.test);
 await phone.evaluate(()=>{const h=__hollowlight;h.test.hold(true);h.test.start('warrior');const g=h.game,w=g.world;w.w=w.h=40;w.grid=Array.from({length:40},()=>Array(40).fill(0));w.portals=[];w.npcs=[];w.shrines=[];w.player.x=15.5;w.player.y=15.5;g.enemies=[];g.items=[];g._msMul=1;});
 const touchRight=phone.locator('[data-touch-key="ArrowRight"]'),touchBox=await touchRight.boundingBox(),cdp=await phoneContext.newCDPSession(phone);
 await check('phone held D-pad stops at pointer release',async()=>{const x=touchBox.x+touchBox.width/2,y=touchBox.y+touchBox.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await phone.evaluate(()=>advanceTime(600));await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const before=await phone.evaluate(()=>({x:__hollowlight.game.world.player.x,y:__hollowlight.game.world.player.y}));await phone.evaluate(()=>advanceTime(500));const after=await phone.evaluate(()=>({x:__hollowlight.game.world.player.x,y:__hollowlight.game.world.player.y}));unchanged(before,after);assert.ok(before.x>20);});
 await check('phone pointer cancellation stops movement',async()=>{const x=touchBox.x+touchBox.width/2,y=touchBox.y+touchBox.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await phone.evaluate(()=>advanceTime(100));await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});const before=await phone.evaluate(()=>({x:__hollowlight.game.world.player.x,y:__hollowlight.game.world.player.y}));await phone.evaluate(()=>advanceTime(500));unchanged(before,await phone.evaluate(()=>({x:__hollowlight.game.world.player.x,y:__hollowlight.game.world.player.y})));});
 const historyPage=await context.newPage();historyPage.on('pageerror',e=>errors.push(e.message));await historyPage.goto(base+'/movement-prior-page');await historyPage.goto(base+'/?test');await historyPage.waitForFunction(()=>window.__hollowlight?.test);await historyPage.evaluate(()=>{__hollowlight.test.start('warrior');__hollowlight.test.hold(true);});
 await check('first actual browser Back opens the menu without leaving play',async()=>{await historyPage.goBack({waitUntil:'domcontentloaded'});await historyPage.waitForFunction(()=>window.__hollowlight?.game.screen==='menu',null,{timeout:5000});assert.equal(new URL(historyPage.url()).pathname,'/');});
 await check('second actual browser Back can leave the app without a history trap',async()=>{await historyPage.goBack({waitUntil:'domcontentloaded'});await historyPage.waitForURL(u=>u.pathname==='/movement-prior-page',{timeout:5000,waitUntil:'domcontentloaded'});});
 await historyPage.goto(base+'/?test');await historyPage.waitForFunction(()=>window.__hollowlight?.test);await historyPage.evaluate(()=>{__hollowlight.test.start('warrior');__hollowlight.test.hold(true);});
 await check('native Back closes a nested inventory screen one level',async()=>{await historyPage.keyboard.press('Escape');await historyPage.locator('[data-action="menu-inventory"]').click();assert.equal(await historyPage.evaluate(()=>__hollowlight.game.screen),'inventory');await historyPage.goBack({waitUntil:'domcontentloaded'});await historyPage.waitForFunction(()=>window.__hollowlight?.game.screen==='menu',null,{timeout:5000});});
 // The exit menu's popstate handler starts a second asynchronous history.back.
 // Await its destination instead of assuming both traversals finish within100ms.
 await check('native Back from the exit menu reaches the prior page',async()=>{await historyPage.goBack({waitUntil:'domcontentloaded'});await historyPage.waitForURL(u=>u.pathname==='/movement-prior-page',{timeout:5000,waitUntil:'domcontentloaded'});});
 await historyPage.goto(base+'/?test');await historyPage.waitForFunction(()=>window.__hollowlight?.test);await historyPage.evaluate(()=>{__hollowlight.test.start('warrior');__hollowlight.test.hold(true);__hollowlight.test.save();});
 await check('reload retains one browser Back guard when Continue resumes',async()=>{const length=await historyPage.evaluate(()=>history.length);await historyPage.reload();await historyPage.waitForFunction(()=>window.__hollowlight?.test);await historyPage.locator('[data-action="title-continue"]').click();await historyPage.evaluate(()=>__hollowlight.test.hold(true));assert.equal(await historyPage.evaluate(()=>history.length),length);await historyPage.goBack({waitUntil:'domcontentloaded'});await historyPage.waitForFunction(()=>window.__hollowlight?.game.screen==='menu',null,{timeout:5000});});
 await check('repeated Resume and native Back do not grow browser history',async()=>{const length=await historyPage.evaluate(()=>history.length);for(let i=0;i<3;i++){await historyPage.locator('[data-action="menu-resume"]').click();await historyPage.evaluate(()=>__hollowlight.test.hold(true));assert.equal(await historyPage.evaluate(()=>history.length),length);await historyPage.goBack({waitUntil:'domcontentloaded'});await historyPage.waitForFunction(()=>window.__hollowlight?.game.screen==='menu',null,{timeout:5000});}});
 await check('held Back repeats cannot resume the menu or exit unexpectedly',async()=>{await historyPage.evaluate(()=>{for(let i=0;i<8;i++)document.dispatchEvent(new KeyboardEvent('keydown',{key:'BrowserBack',repeat:true,bubbles:true,cancelable:true}));});assert.equal(await historyPage.evaluate(()=>window.__hollowlight?.game.screen),'menu');});
 await check('repeated menu cycles still allow a final native Back exit',async()=>{await historyPage.goBack({waitUntil:'domcontentloaded'});await historyPage.waitForURL(u=>u.pathname==='/movement-prior-page',{timeout:5000,waitUntil:'domcontentloaded'});});
 await page.evaluate(async()=>{if(window.__GL?.ready)await __GL.ready;__hollowlight.test.start('warrior');__hollowlight.test.hold(true);advanceTime(16);});await page.waitForFunction(()=>window.__GL?._dbg?.().rendererInfo?.calls>0);await page.screenshot({path:path.join(out,'town.png')});
 await phone.evaluate(async()=>{if(window.__GL?.ready)await __GL.ready;__hollowlight.test.start('warrior');__hollowlight.test.hold(true);advanceTime(16);});await phone.screenshot({path:path.join(out,'phone-town.png')});
 await check('no runtime errors or external/cloud requests',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(outbound,[]);});
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,metrics,errors,outbound},null,2));console.log(JSON.stringify({passed:checks.filter(c=>c.pass).length,total:checks.length,failed:checks.filter(c=>!c.pass),metrics,errors}));await browser.close();if(checks.some(c=>!c.pass))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
