const fs=require('node:fs'),path=require('node:path');
const {chromium}=require(path.join(require('node:os').homedir(),'.codex/skills/develop-web-game/node_modules/playwright'));
const report={checks:[],maps:[],errors:[]};const out=process.env.SPIRE_SCENERY_EVIDENCE||path.resolve(__dirname,'../../.visual-review/spire-feel/scenery/regression');fs.mkdirSync(out,{recursive:true});const target=new URL(process.env.SPIRE_URL||'http://127.0.0.1:5265');if(!['127.0.0.1','localhost'].includes(target.hostname))throw Error('Scenery tests require an isolated loopback server');target.searchParams.set('test','1');
function check(name,pass,detail){report.checks.push({name,pass,detail});}
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const c=await browser.newContext({viewport:{width:600,height:600},serviceWorkers:'block'});await c.route('**/*',r=>['127.0.0.1','localhost'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(target.href);await p.waitForFunction(()=>window.__hollowlight?.test&&window.__GL?.ready);
 await p.evaluate(async()=>{await __GL.ready;__hollowlight.test.start('warrior');__hollowlight.test.hold(true);window.__build=(await import('./spire-world.js')).buildWorldArt;window.__dispose=g=>{const m=new Set();g.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)m.add(o.material);});for(const x of m)x.dispose();};window.__signature=g=>{let h=2166136261,n=0;g.traverse(o=>{if(!o.geometry)return;for(const a of Object.values(o.geometry.attributes))for(const v of a.array){h=Math.imul(h^Math.round(v*100000),16777619)>>>0;n++;}});return h+':'+n;};});
 for(const biome of ['crypts','overgrowth','frostpeak','infernal','tempest','voidspire'])for(const floor of [1,2,3,4]){
  const row=await p.evaluate(({biome,floor})=>{const h=__hollowlight,g=h.game;h.enterBiome(biome,floor);h.test.hold(true);const w=g.world,before=JSON.stringify(w),originalRandom=Math.random;let calls=0,art;Math.random=()=>{calls++;return .25};try{art=__build(w)}finally{Math.random=originalRandom}
   const data=art.userData.scenery;let finite=true,degenerate=0;art.traverse(o=>{if(!o.geometry)return;const a=o.geometry.getAttribute('position').array;finite&&=[...a].every(Number.isFinite)&&Number.isFinite(o.geometry.boundingSphere.radius);for(let i=0;i<a.length;i+=9){const ux=a[i+3]-a[i],uy=a[i+4]-a[i+1],uz=a[i+5]-a[i+2],vx=a[i+6]-a[i],vy=a[i+7]-a[i+1],vz=a[i+8]-a[i+2];if(Math.hypot(uy*vz-uz*vy,uz*vx-ux*vz,ux*vy-uy*vx)<1e-8)degenerate++;}});
   const bad=[];for(const prop of data.props)for(let y=Math.floor(prop.min[1]);y<=Math.floor(prop.max[1]);y++)for(let x=Math.floor(prop.min[0]);x<=Math.floor(prop.max[0]);x++)if(!w.grid[y]||w.grid[y][x]===undefined||w.grid[y][x]===0)bad.push(prop);
   const targets=[w.player,...w.portals,...w.shrines,...w.npcs].filter(Boolean),targetOverlap=data.props.filter(a=>targets.some(t=>Math.hypot(a.x-t.x,a.z-t.y)<=2.1));
   const sig=__signature(art);let second;Math.random=()=>.75;try{second=__build(w)}finally{Math.random=originalRandom}const same=sig===__signature(second);__dispose(art);__dispose(second);return {biome,floor,unchanged:JSON.stringify(w)===before,threeUuidRandomCalls:calls,finite,degenerate,bad:bad.length,targetOverlap:targetOverlap.length,deterministic:same,props:data.props.length,floorDetails:data.floorDetails,rooms:data.rooms.length};
  },{biome,floor});report.maps.push(row);check(biome+' floor'+floor+' collision/targets/random-invariant geometry',row.unchanged&&row.finite&&!row.degenerate&&!row.bad&&!row.targetOverlap&&row.deterministic,row);
 }
 report.cycles=await p.evaluate(()=>{const g=__hollowlight.game,a=[];for(let i=0;i<10;i++){__GL.onZoneChange(g.world);__GL.frame(g,20000+i*16);a.push(__GL._dbg().rendererInfo);}return a;});check('Repeated world rebuilds retain stable GPU resources',report.cycles.slice(2).every(a=>a.geometries===report.cycles[2].geometries&&a.textures===report.cycles[2].textures),report.cycles);
 report.buffer=await p.evaluate(()=>({w:document.querySelector('#game-canvas-gl')?.width,h:document.querySelector('#game-canvas-gl')?.height,canvases:[...document.querySelectorAll('canvas')].map(c=>({id:c.id,w:c.width,h:c.height}))}));check('Fixed 600px render buffer',report.buffer.w===600&&report.buffer.h===600,report.buffer);check('No runtime browser errors',!report.errors.length,report.errors);
}catch(e){report.error=e.stack;process.exitCode=1}finally{await browser.close();report.failed=report.checks.filter(c=>!c.pass);report.passed=!report.error&&!report.failed.length;fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,error:report.error,checks:report.checks.length,failed:report.failed,buffer:report.buffer}));if(!report.passed)process.exitCode=1;}})();
